config/routes.rb
Rails.application.routes.draw do

  resources :listings
  resources :bookings
  devise_for :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :host, class_name: 'User'

  def full_address
    [address, city, state].join(', ')
  end

  def country
    ISO3166::Country.new(country_code)
  end

  def country_code_upper
    country_code.upcase
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    listing = Listing.find(params[:listing]) #verifying listing
    @booking.listing_id = listing
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.guest = current_user
    # Validate dates and guest count
    if booking.invalid?
      render :new
      return
    end

    # Amount in cents
  @amount = listing.price * 100

# Add user to Strip Database
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )
# Charge the user via Stripe
  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => listing.full_address,
    :currency    => 'usd'
  )


    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end

      rescue Stripe::CardError => e
      flash[:error] = e.message
      # redirect_to new_charge_path
      render :new 
      end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:guest_id, :listing_id, :check_in_at, :check_out_at, :guest_count, :stripe_charge_id, :special_requirement)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    @countries =  ISO3166::Country.codes.map { |country_code| ISO3166::Country.new(country_code) }
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.host = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :price, :address, :city, :state, :country_code, :max_guests, :rooms, :beds, :shared, :min_nights, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% f.hidden :listing_id %>

  <div class="field">
    <%= f.label :check_in_at %>
    <%= f.date_select :check_in_at %>
  </div>

  <div class="field">
    <%= f.label :check_out_at %>
    <%= f.date_select :check_out_at %>
  </div>

  <div class="field">
    <%= f.label :guest_count %>
    <%= f.number_field :guest_count %>
  </div>


  <div class="field">
    <%= f.label :special_requirement %>
    <%= f.text_area :special_requirement %>
  </div>

  <div class="actions">
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Guest</th>
      <th>Listing</th>
      <th>Check in at</th>
      <th>Check out at</th>
      <th>Guest count</th>
      <th>Stripe charge</th>
      <th>Special requirement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.guest %></td>
        <td><%= booking.listing %></td>
        <td><%= booking.check_in_at %></td>
        <td><%= booking.check_out_at %></td>
        <td><%= booking.guest_count %></td>
        <td><%= booking.stripe_charge_id %></td>
        <td><%= booking.special_requirement %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guest:</strong>
  <%= @booking.guest.email %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @booking.listing.full_address %>
</p>

<p>
  <strong>Check in at:</strong>
  <%= @booking.check_in_at %>
</p>

<p>
  <strong>Check out at:</strong>
  <%= @booking.check_out_at %>
</p>

<p>
  <strong>Guest count:</strong>
  <%= @booking.guest_count %>
</p>

<p>
  <strong>Stripe charge:</strong>
  <%= @booking.stripe_charge_id %>
</p>

<p>
  <strong>Special requirement:</strong>
  <%= @booking.special_requirement %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waterbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav/primary' %>

    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country_code_upper, 'Country' %>
    <%= f.collection_select :country_code_upper, @countries, :alpha2, :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :max_guests %>
    <%= f.number_field :max_guests %>
  </div>

  <div class="field">
    <%= f.label :rooms %>
    <%= f.number_field :rooms %>
  </div>

  <div class="field">
    <%= f.label :beds %>
    <%= f.number_field :beds %>
  </div>

  <div class="field">
    <%= f.label :shared %>
    <%= f.check_box :shared %>
  </div>

  <div class="field">
    <%= f.label :min_nights %>
    <%= f.number_field :min_nights %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Price</th>
      <th>Long</th>
      <th>Lat</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country code</th>
      <th>Max guests</th>
      <th>Rooms</th>
      <th>Beds</th>
      <th>Shared</th>
      <th>Min nights</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.host %></td>
        <td><%= listing.price %></td>
        <td><%= listing.long %></td>
        <td><%= listing.lat %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.state %></td>
        <td><%= listing.country_code %></td>
        <td><%= listing.max_guests %></td>
        <td><%= listing.rooms %></td>
        <td><%= listing.beds %></td>
        <td><%= listing.shared %></td>
        <td><%= listing.min_nights %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Book now', new_booking_path(listing: @listing.id) %>

<p>
  <strong>Hosted by:</strong>
  <%= @listing.host.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.full_address %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country.emoji_flag %>
  <%= @listing.country.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Max guests:</strong>
  <%= @listing.max_guests %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @listing.rooms %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @listing.beds %>
</p>

<p>
  <strong>Shared:</strong>
  <%= @listing.shared %>
</p>

<p>
  <strong>Min nights:</strong>
  <%= @listing.min_nights %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/nav/_primary.html.erb
<nav>
  <% if user_signed_in? %>
    <%= link_to('Account', edit_user_registration_path) %>
    <%= link_to('Log out', destroy_user_session_path, :method => :delete) %>        
  <% else %>
    <%= link_to('Sign up', new_user_registration_path)  %>
    <%= link_to('Log in', new_user_session_path)  %>  
  <% end %>
</nav>